name: Build and Deploy Book
on:
  push:
    branches:
    - main
  schedule:
  - cron: 0 15 * * *
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install --upgrade pip; pip install -r requirements.txt
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton";git
        pull --tags
    - name: Build the book
      run: dz load-explorer-data && dz build-explorer
      env:
        ZIMMER_AUTH_HEX: ${{ secrets.ZIMMER_AUTH_HEX }}
        ZIMMER_PHRASE: ${{ secrets.ZIMMER_PHRASE }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
        ASWAN_AUTH_PASS: ${{ secrets.ASWAN_AUTH_PASS }}
        ASWAN_AUTH_HEX: ${{ secrets.ASWAN_AUTH_HEX }}
        ASWAN_REMOTE: ${{ secrets.ASWAN_REMOTE }}
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html
